name: eco_adventure
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.2.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  go_router: ^9.0.0
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_polyline_points:
    path: ./flutter_polyline_points

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
